name: ${PROJECT_NAME}
services:
  frontend:
    container_name: ${PROJECT_NAME}-frontend
    build: .
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - NGINX_PROXY=http://${PROJECT_NAME}-backend:${BACKEND_PORT}
      - NGINX_PORT=${FRONTEND_PORT}
    networks:
      - pf-net
networks:
  pf-net:
    name: ${PROJECT_NAME}-net
    external: true
